version: "3.9"
services:
  app:
    build: .
    container_name: flask
    command: flask run
    restart: always
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    ports:
      - 127.0.0.1:5000:5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
